# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RA_Gui.ui'
#
# Created: Fri Apr 20 00:32:42 2012
#      by: pyside-uic 0.2.11 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 650)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 431, 743))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Table = QtGui.QPushButton(self.layoutWidget)
        self.Table.setObjectName("Table")
        self.verticalLayout.addWidget(self.Table)
        self.TableSlider = QtGui.QSlider(self.layoutWidget)
        self.TableSlider.setMaximum(10)
        self.TableSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TableSlider.setObjectName("TableSlider")
        self.verticalLayout.addWidget(self.TableSlider)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Chair = QtGui.QPushButton(self.layoutWidget)
        self.Chair.setObjectName("Chair")
        self.verticalLayout.addWidget(self.Chair)
        self.ChairSlider = QtGui.QSlider(self.layoutWidget)
        self.ChairSlider.setMaximum(10)
        self.ChairSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ChairSlider.setObjectName("ChairSlider")
        self.verticalLayout.addWidget(self.ChairSlider)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.Refrigerator = QtGui.QPushButton(self.layoutWidget)
        self.Refrigerator.setObjectName("Refrigerator")
        self.verticalLayout.addWidget(self.Refrigerator)
        self.RefrigeratorSlider = QtGui.QSlider(self.layoutWidget)
        self.RefrigeratorSlider.setMaximum(10)
        self.RefrigeratorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RefrigeratorSlider.setObjectName("RefrigeratorSlider")
        self.verticalLayout.addWidget(self.RefrigeratorSlider)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.Bed = QtGui.QPushButton(self.layoutWidget)
        self.Bed.setObjectName("Bed")
        self.verticalLayout.addWidget(self.Bed)
        self.BedSlider = QtGui.QSlider(self.layoutWidget)
        self.BedSlider.setMaximum(10)
        self.BedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BedSlider.setObjectName("BedSlider")
        self.verticalLayout.addWidget(self.BedSlider)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.Bookshelf = QtGui.QPushButton(self.layoutWidget)
        self.Bookshelf.setObjectName("Bookshelf")
        self.verticalLayout.addWidget(self.Bookshelf)
        self.BookshelfSlider = QtGui.QSlider(self.layoutWidget)
        self.BookshelfSlider.setMaximum(10)
        self.BookshelfSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BookshelfSlider.setObjectName("BookshelfSlider")
        self.verticalLayout.addWidget(self.BookshelfSlider)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.Closet = QtGui.QPushButton(self.layoutWidget)
        self.Closet.setObjectName("Closet")
        self.verticalLayout.addWidget(self.Closet)
        self.ClosetSlider = QtGui.QSlider(self.layoutWidget)
        self.ClosetSlider.setMaximum(10)
        self.ClosetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ClosetSlider.setObjectName("ClosetSlider")
        self.verticalLayout.addWidget(self.ClosetSlider)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.Lamp = QtGui.QPushButton(self.layoutWidget)
        self.Lamp.setObjectName("Lamp")
        self.verticalLayout.addWidget(self.Lamp)
        self.LampSlider = QtGui.QSlider(self.layoutWidget)
        self.LampSlider.setMaximum(10)
        self.LampSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LampSlider.setObjectName("LampSlider")
        self.verticalLayout.addWidget(self.LampSlider)
        self.line_7 = QtGui.QFrame(self.layoutWidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.Handle = QtGui.QPushButton(self.layoutWidget)
        self.Handle.setObjectName("Handle")
        self.verticalLayout.addWidget(self.Handle)
        self.HandleSlider = QtGui.QSlider(self.layoutWidget)
        self.HandleSlider.setMaximum(10)
        self.HandleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.HandleSlider.setObjectName("HandleSlider")
        self.verticalLayout.addWidget(self.HandleSlider)
        self.line_8 = QtGui.QFrame(self.layoutWidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 934, 25))###
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #PySide.QtGui.QWidget.sizeHint() ###
        #PySide.QtGui.QWidget.childrenRect()###


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Table.setText(QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.Chair.setText(QtGui.QApplication.translate("MainWindow", "Chair", None, QtGui.QApplication.UnicodeUTF8))
        self.Refrigerator.setText(QtGui.QApplication.translate("MainWindow", "Refrigerator", None, QtGui.QApplication.UnicodeUTF8))
        self.Bed.setText(QtGui.QApplication.translate("MainWindow", "Bed", None, QtGui.QApplication.UnicodeUTF8))
        self.Bookshelf.setText(QtGui.QApplication.translate("MainWindow", "Bookshelf", None, QtGui.QApplication.UnicodeUTF8))
        self.Closet.setText(QtGui.QApplication.translate("MainWindow", "Closet", None, QtGui.QApplication.UnicodeUTF8))
        self.Lamp.setText(QtGui.QApplication.translate("MainWindow", "Lamp", None, QtGui.QApplication.UnicodeUTF8))
        self.Handle.setText(QtGui.QApplication.translate("MainWindow", "Handle", None, QtGui.QApplication.UnicodeUTF8))

